
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 28 12:19:19 CST 2013
//----------------------------------------------------

package syn;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int USTAR = 58;
  public static final int SHR_ASSIGN = 38;
  public static final int SHR = 24;
  public static final int DIVIDE = 5;
  public static final int XOR_ASSIGN = 31;
  public static final int LBRACKET = 18;
  public static final int CHAR = 45;
  public static final int SHL = 23;
  public static final int Chr = 66;
  public static final int GE = 12;
  public static final int UMINUS = 60;
  public static final int UTILDE = 61;
  public static final int PLUS_ASSIGN = 33;
  public static final int SELFPLUS = 20;
  public static final int UPLUS = 59;
  public static final int XOR = 26;
  public static final int CONTINUE = 51;
  public static final int LPAREN = 13;
  public static final int UNOT = 62;
  public static final int UAND = 57;
  public static final int INT = 54;
  public static final int FOR = 50;
  public static final int MINUS = 3;
  public static final int TOWARDS = 63;
  public static final int RPAREN = 14;
  public static final int SIZEOF = 53;
  public static final int SEMICOLON = 17;
  public static final int AND = 27;
  public static final int LT = 9;
  public static final int SELFMINUS = 21;
  public static final int OR = 25;
  public static final int ELLIPSIS = 40;
  public static final int COMMA = 22;
  public static final int LOGIC_AND = 42;
  public static final int NUM = 64;
  public static final int TYPEDEF = 43;
  public static final int PLUS = 2;
  public static final int IF = 55;
  public static final int ASSIGN = 6;
  public static final int ID = 65;
  public static final int LE = 11;
  public static final int EOF = 0;
  public static final int RETURN = 56;
  public static final int RBRACKET = 19;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 37;
  public static final int MOD = 28;
  public static final int BREAK = 52;
  public static final int VOID = 44;
  public static final int EQ = 7;
  public static final int MOD_ASSIGN = 36;
  public static final int String_const = 67;
  public static final int LOGIC_OR = 41;
  public static final int TIMES = 4;
  public static final int UNION = 47;
  public static final int ELSE = 48;
  public static final int TIMES_ASSIGN = 29;
  public static final int LBRACE = 15;
  public static final int AND_ASSIGN = 32;
  public static final int POINT = 39;
  public static final int WHILE = 49;
  public static final int DIVIDE_ASSIGN = 35;
  public static final int OR_ASSIGN = 30;
  public static final int RBRACE = 16;
  public static final int NE = 8;
  public static final int STRUCT = 46;
  public static final int GT = 10;
  public static final int MINUS_ASSIGN = 34;
}

