
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 07 10:07:34 CST 2013
//----------------------------------------------------

package syn;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int TIMES = 2;
  public static final int LT = 4;
  public static final int SEMICOLON = 9;
  public static final int RBRACE = 8;
  public static final int RPAREN = 6;
  public static final int INT = 16;
  public static final int String_const = 20;
  public static final int RETURN = 17;
  public static final int LPAREN = 5;
  public static final int LBRACKET = 10;
  public static final int LBRACE = 7;
  public static final int ID = 19;
  public static final int RBRACKET = 11;
  public static final int NUM = 18;
  public static final int SELFPLUS = 12;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int PLUS_ASSIGN = 14;
  public static final int error = 1;
  public static final int ASSIGN = 3;
  public static final int FOR = 15;
}

